@url = http://localhost:8080

GET {{url}}/users
###
POST {{url}}/auth/login
Content-Type: application/json

{
    "Correo": "cddd@miumg.edu.gt",
    "pass": "123"
}

###
GET {{url}}/17
###
POST {{url}}/users
Content-Type: application/json

{
    "Nombres": "randal",
    "Correo": "cddd@miumg.edu.gt",
    "pass": "123",
    "Estado": "A"
}

###
PUT {{url}}/30
Content-Type: application/json

{
    "Nombres": "ramazinccci",
    "Correo": "cmauin@miumg.edu.gt",
    "pass": "12347",
    "Estado": "A"
}

###
DELETE {{url}}/2
